version: '3.8'

services:
  app:
    build: .
    container_name: learn-java-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres
    networks:
      - learn-java-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:18-alpine
    container_name: learn-java-postgres
    environment:
      POSTGRES_DB: learndb
      POSTGRES_USER: learn_user
      POSTGRES_PASSWORD: learn_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - learn-java-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U learn_user -d learndb"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: learn-java-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - learn-java-network
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: learn-java-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - learn-java-network
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_data:

networks:
  learn-java-network:
    driver: bridge
